apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentd.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "fluentd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  fluent.conf: |-
{{ .Values.fluentConf | indent 4 }}
